alias: FrontPorch Auto
blueprint:
  name: Motion-activated Device
  description: Turn on a light when motion is detected.
  domain: automation
  source_url: https://github.com/Jeremyy0/HomeAssistant/Lights_with_Camera.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds


description: Turn on Porch Lights with Motion Detection
trigger:
  - type: motion
    platform: device
    device_id: a56d00763295c8f406e5e6ed14a62d28
    entity_id: binary_sensor.motion_front_door
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 2
condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
action:
  - type: turn_on
    device_id: 9286837d2a9527d51b9bcfb9d090f096
    entity_id: switch.32100611c82b96441b08
    domain: switch
  - wait_for_trigger:
      - type: no_motion
        platform: device
        device_id: a56d00763295c8f406e5e6ed14a62d28
        entity_id: binary_sensor.motion_front_door
        domain: binary_sensor
        for:
          hours: 0
          minutes: 5
          seconds: 0
  - type: turn_off
    device_id: 9286837d2a9527d51b9bcfb9d090f096
    entity_id: switch.32100611c82b96441b08
    domain: switch
mode: single
