alias: FrontPorch Auto
blueprint:
  name: Motion-activated Device
  description: Turn on a light when motion is detected.
  domain: automation
  source_url: https://github.com/Jeremyy0/HomeAssistant/blob/main/Blueprints/Lights_with_Camera_motion.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    device_target:
      name: Device
      selector:
        target:
          entity:
            domain: switch
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 5
      selector:
        number:
          min: 0
          max: 60
          unit_of_measurement: minutes


description: Turn on Porch Lights with Motion Detection
trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"
condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
action:
  - type: turn_on
    entity_id: !input device_target
    domain: switch
  - wait_for_trigger:
      - type: no_motion
        platform: device
        device_id: a56d00763295c8f406e5e6ed14a62d28
        entity_id: binary_sensor.motion_front_door
        domain: binary_sensor
        for:
          hours: 0
          minutes: !input no_motion_wait
          seconds: 0
  - type: turn_off
    entity_id: !input device_target
    domain: switch
mode: single
