blueprint:
  name: SimpliSafeDoorAlerts
  description: Send voice alerts to gooogle home when SimpliSafe sensor's are triggered.
  domain: automation
  source_url: https://github.com/Jeremyy0/HomeAssistant/blob/main/Blueprints/SimpliSafeDoorAlerts.yaml
  input:
    sensor_entity:
      name: Door Sensor
      selector:
        entity:
          domain: binary_sensor
          #device_class: entry
    tts_message:
      name: Text-To-Speech Alert Message
      default: "Door opened"
      selector:
        text:
          multiline: true

# If motion is detected within the delay,
# we restart the script.
max_exceeded: silent

trigger:
  - type: opened
    platform: device
    entity_id: !input sensor_entity
    domain: binary_sensor
condition: []
action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.office_speaker
      message: !input tts_message
mode: restart
